"use client";

import React from "react";
import { Sparkles, Loader2 } from "lucide-react";
import { Project } from "@/types/project";

import { useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { useEffect, useState } from "react";

export function BrandSummary({ project }: { project: Project | null }) {
  const [isGenerating, setIsGenerating] = useState(false);
  const qc = useQueryClient();

  const handleGenerate = async () => {
    if (!project?.id) return;
    setIsGenerating(true);
    try {
      const res = await fetch("/api/jobs/generate-brand-summary", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ projectId: project.id }),
      });

      if (!res.ok) throw new Error("Failed to generate summary");
      await qc.invalidateQueries({ queryKey: ["projects"] });
    } catch (err: any) {
      toast.error(err?.message || "Failed to generate brand summary");
    } finally {
      setIsGenerating(false);
    }
  };

  useEffect(() => {
    if (project?.id && !project?.brand_description && !isGenerating) {
      handleGenerate();
    }
  }, [project?.id, project?.brand_description]);

  const getCleanDescription = (desc?: string | null) => {
    if (!desc) return "";
    return desc.split("\n---\nMETADATA: ")[0];
  };

  return (
    <div className="bg-indigo-50/50 rounded-xl border border-indigo-100 p-6 h-full flex flex-col justify-between relative overflow-hidden">
      <div className="absolute top-0 right-0 p-4 opacity-5 pointer-events-none">
        <Sparkles className="w-24 h-24 text-indigo-600" />
      </div>
      <div>
        <h3 className="font-bold text-slate-900 flex items-center gap-2">
          <Sparkles className="w-4 h-4 text-indigo-600" />
          AI Brand Summary
        </h3>
        
        {isGenerating ? (
          <div className="mt-8 flex flex-col items-center justify-center gap-2 py-4">
            <Loader2 className="w-6 h-6 animate-spin text-indigo-600" />
            <p className="text-xs font-bold text-slate-500 uppercase tracking-wider">AI is crafting your summary...</p>
          </div>
        ) : getCleanDescription(project?.brand_description) ? (
          <p className="mt-4 text-sm font-semibold text-slate-700 leading-relaxed relative z-10">
            {getCleanDescription(project?.brand_description)}
          </p>
        ) : (
          <div className="mt-6 text-center py-4 relative z-10">
            <p className="text-xs text-slate-550 font-semibold leading-relaxed mb-4">
              AI brand summary has not been generated yet. Click <strong className="text-indigo-600">Refresh Brand Data</strong> in the Quick Actions panel to initiate the brand scan.
            </p>
          </div>
        )}
      </div>
      
      <div className="mt-6 flex items-center gap-2">
        <span className="px-2.5 py-1 rounded-md bg-indigo-100 text-indigo-700 text-[10px] font-bold flex items-center gap-1">
          <Sparkles className="w-3 h-3" /> Generated by SoloSpider AI
        </span>
      </div>
    </div>
  );
}
